### PR TITLE
Pagination class PATCH Updated ``StreamedPaginatedListMixin``

### PR DESCRIPTION
**Pull request by lautarodapin**
Updated the condition to send another result

### CODE REVIEW

**Comment by lautarodapin** [comment]
While using it, I found that I always got an empty response at last.

**Comment by hishnash** [comment]
I think best is just to stop sending when we complete. They can subclass the pagniator to add a number of expected pages if they want.

**Comment by lautarodapin** [comment]
Ok, should we add a method to override for those cases?

**Comment by jhillacre** [comment]
Seems like it would be useful for `dcrf-client` (theY4Kman/dcrf-client#22) to have the last response indicated as the last response, so a list callback can be cleaned up.

I would love to see this and #71 in a new release tag.

**Comment by lautarodapin** [comment]
> I would love to see this and #71 in a new release tag.

I support this 😅

**Pull request merged**
