### PR TITLE
Add documentation link

### PR DESCRIPTION
**Pull request by lautarodapin**
[documentation](https://djangochannelsrestframework.readthedocs.io/en/latest/)

### CODE REVIEW

**Comment by hishnash** [comment]
Might be worth removing the docs from the readme and just linking out to the full docs this way we just have one place to maintain and update.

**Comment by hishnash** [comment]
would you be able to transfer those docs over to my username on read the docs so that I can publish them as i push out new releases?

**Comment by lautarodapin** [comment]
> would you be able to transfer those docs over to my username on read the docs so that I can publish them as i push out new releases?
> 

Do you have an account so I can add youm

**Comment by lautarodapin** [comment]
> Yep, `hishnash` same is GitHub.

Done

**Review by hishnash — APPROVED** [review]

**Pull request merged**
